apiVersion: v1
kind: Service
metadata:
  name: netfilx-service
  namespace: prod
  labels:
    author: Tawfeeq
spec:
  type: ClusterIP
  selector: 
    app: netflix-app
  ports:
    - targetPort: 3000
      port: 80
      protocol: TCP
